app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField,SelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from app.models import User, Category
from flask_login import current_user
from flask_wtf.file import FileField, FileAllowed


# Form for Creating and Updating Posts
class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    
    allCategories = Category.query.all()
    valueLabelPair = [(category.id,category.category) for category in allCategories]
    category = SelectField('Category', choices = valueLabelPair)

    submit = SubmitField('Post')

# Form for Creating and Updating Posts
class CommentForm(FlaskForm):
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Comment')

app/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from app.extensions import db
from app.models import Post, Comment, Category
from app.posts.forms import PostForm, CommentForm

posts = Blueprint('posts',__name__)

#### ROUTES FOR CRUD operations Post ####
# CREATE new Post Route
@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()

    # print(dict(form.category.choices).get(form.category.data))
    if form.validate_on_submit():
        # labelOfSelectField = dict(form.category.choices).get(int(form.category.data))
        category = Category.query.get_or_404(form.category.data)   # Get the Post or return 404 if post not exist
        post = Post(title=form.title.data, content=form.content.data, author=current_user, category=category)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')

# READ Post
@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    form = CommentForm()                    # Form for posting a Comment
    post = Post.query.get_or_404(post_id)   # Get the Post or return 404 if post not exist

    #If Comment is pushed add the comment to the database
    if form.validate_on_submit():
        comment = Comment(comment=form.content.data,thread=post,user_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('posts.post',post_id=post.id))

    return render_template('post.html', title=post.title, post=post,commentForm=form)

# UPDATE Post
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')

# DELETE Post
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

# Get All Posts for given category
@posts.route("/post/filter/<int:category>")
def filter_posts(category):
    page = request.args.get('page', 1, type=int)
    category = Category.query.get_or_404(category)   # Get the Post or return 404 if post not exist

    posts = Post.query.filter_by(category=category)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('filter_posts.html', posts=posts, category=category)

app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app.extensions import db, bcrypt
from app.models import User, Post
from app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm)
from app.users.utils import save_picture, send_reset_email

users = Blueprint('users',__name__)

# Register Page
@users.route("/register", methods=['GET','POST'])
def register():

    # If user already is logged in return to home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm() # Initialize Registration FOrm and pass it to html template
    
    # Ths will check if it is a POST request and if it is valid.
    if form.validate_on_submit():
        # Create User Object (account) and save to Database
        # Before saving user details, password should be hashed
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8') # UTF-8 makes the hash string instead of bytes
        newUser = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(newUser)
        db.session.commit()

        flash(f'Account created, you can now log in!', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', title='Register', form=form)

# Login Page
@users.route("/login", methods=['GET','POST'])
def login():

    # If user already is logged in return to home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm() # Initialize Login FOrm and pass it to html template

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # If a user with given email exists and password is correct login
        if user and bcrypt.check_password_hash(user.password,form.password.data):
             login_user(user, remember=form.remember.data)   # FLaskLogin handles all sessions stuff
             flash(f'Logged in succesfully', 'success')

             next_page = request.args.get('next')

             return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
             flash(f'The combination of Email and Password is not correct, Try again', 'danger')

    return render_template('login.html', title='Login', form=form)

# Logout Route
@users.route("/logout")
def logout():
    logout_user()
    flash(f'Logged out succesfully', 'info')
    return redirect(url_for('main.home'))

# My Acount route
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        # If there is a profile pic passed save it
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        # Load with initial values if GET request
        form.username.data = current_user.username
        form.email.data = current_user.email
         # Get latest post of user
        latestPosts = Post.query.filter_by(author=current_user).order_by(Post.date_posted.desc()).limit(6).all()

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form, user=current_user,latestPosts=latestPosts)

# Visit Other users Account
@users.route("/account/<int:userid>", methods=['GET', 'POST'])
@login_required
def account_user(userid):
    user = User.query.get_or_404(userid)   # Get the User
    print(user)
    if current_user == user:
        return redirect(url_for('users.account'))

    # Get latest post of user
    latestPosts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).limit(6).all()

    image_file = url_for('static', filename='profile_pics/' + user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, user=user,latestPosts=latestPosts)

# Get All Posts for given username
@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

#### ROUTES FOR RESET_PASSWORD and Sending mail with token ####
# Send password reset request via mail and generate token
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

# Verify token and Reset password route
@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

app/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

app/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>

        {% if current_user == user  %}
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
        {% endif %}
    </div>
{% endblock content %}


{% block sidebar %}
  <div class="content-section">
      <ul class="list-group">
        <li class="list-group-item list-group-item-light">Posts of User: {{user.username}}</li>
        
        {% for post in latestPosts %}
          <article class="media content-section mt-1">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.account_user', userid=post.author.id) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              </div>
              <h6><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></hr6>
            </div>
          </article>
          <div class='col-12'>
            <a class="" href="{{ url_for('users.user_posts', username=post.author.username) }}">See all Posts of User</a>
          </div>
        {% endfor %}
        <!-- <li class="list-group-item list-group-item-light">Announcements</li>
        <li class="list-group-item list-group-item-light">Calendars</li>
        <li class="list-group-item list-group-item-light">etc</li> -->
      </ul>
    </p>
  </div>

{% endblock sidebar %}

app/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid", id='editor') }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg", id='editor') }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.category.label(class="form-control-label") }}
                {{ form.category(class="form-control form-control-lg") }}
                </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

app/templates/filter_posts.html
{% extends "layout2.html" %}
{% block content %}
    <h3 class="mb-3">Posts for Category: {{ category.category }} ({{ posts.total }})</h3>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.account_user', userid=post.author.id) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('posts.filter_posts', category=category.id, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('posts.filter_posts', category=category.id, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

app/templates/home.html
{% extends "layout.html" %}


{% block content %}
    {% for category in categories %}
        <article class="media content-section">
          <div class="media-body">

            <div class='row mt-1'>
              <div class='col-md-1 '>
                <img class="" width='50px' height='50px' src="{{ url_for('static', filename='icons/chat.png') }}">
              </div>
              <div class='col-md-8'>
                <h4 ><a class="article-title" href="{{url_for('posts.filter_posts',category=category.id)}}">{{ category.category }}</a></h4>
                <p><span class='text-muted'>Threads:</span> {{category.threads}}</p>
              </div>
            </div>

          </div>
        </article>
    {% endfor %}

{% endblock content %}


{% block sidebar %}
  <div class="content-section">
      <ul class="list-group">
        <li class="list-group-item list-group-item-light">Latest Posts</li>
        
        {% for post in latestPosts %}
          <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.account_user', userid=post.author.id) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              </div>
              <h6><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></hr6>
            </div>
          </article>
        {% endfor %}
        <!-- <li class="list-group-item list-group-item-light">Announcements</li>
        <li class="list-group-item list-group-item-light">Calendars</li>
        <li class="list-group-item list-group-item-light">etc</li> -->
      </ul>
    </p>
  </div>

{% endblock sidebar %}

{% block toprow %}
<div class='col-8'>
  <h3>Atom Forum</h3>
</div>
<div class='col-4'>
  <a class="nav-item nav-link float-right btn btn-primary" href="{{ url_for('posts.new_post') }}">New Post</a>
</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom Css -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>

    <!-- Navbar -->
    {% include 'includes/navbar.html' %}

    <main role="main" class="container">
      <div class='row m-2'>
        {% block toprow %}
        {% endblock %}
      </div>
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          {% block sidebar %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="//cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
    <script type='text/javascript'>
      CKEDITOR.replace('editor')
    </script>
  </body>
</html>

app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class='content-section'>
        <form method='POST' action=''>
            <!-- Some security or something uses Secret Key and protects Form -->
            {{ form.hidden_tag() }}

            <fieldset class='form-group'>
                <legend class='border-bottom mb-4'>Login</legend>
                <div class='form-group'>
                    {{ form.email.label(class='form-control-label') }}

                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                             {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                             {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}


                </div>
                <div class='form-group'>
                    {{ form.password.label(class='form-control-label') }}

                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                             {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                             {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                
                <div class='form-check'>
                    {{ form.remember(class='form-check-input') }}
                    {{ form.remember.label(class='form-check-label') }}
                </div>
            </fieldset>
            <div class='form-group'>
                {{ form.submit(class='btn btn-outline-info') }}
                <small class='text-muted ml-2'>
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>

        </form>
    </div>

    <div class='border-top pt-3'>
        <small class='text-muted'>
            No account yet? <a href='{{url_for("users.register")}}' class='ml-2'>Register</a> 
        </small>
    </div>

{% endblock content %}

app/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content|safe }}</p>
    </div>
  </article>

  <div class="bg-white p-3">
      {% if current_user.is_authenticated %}
      <form method="POST" action="">
          {{ commentForm.hidden_tag() }}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Place a Comment</legend>
              <div class="form-group">
                  {{ commentForm.content.label(class="form-control-label") }}
                  {% if commentForm.content.errors %}
                      {{ commentForm.content(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in commentForm.content.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}  
                      {{ commentForm.content(class="form-control form-control-lg") }}
                  {% endif %}
              </div>
          </fieldset>
          <div class="form-group">
              {{ commentForm.submit(class="btn btn-outline-info") }}
          </div>
      </form>
      <hr>
      {% else %}
      <p> Sign in to place Comments</p>
      {% endif %}

      <div class="media-body">
        <h4>Comments</h4>
          {% for comment in post.comments %}
          <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + comment.authorCom.image_file) }}">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.account_user', userid=post.author.id) }}">{{ comment.authorCom.username }}</a>
                <small class="text-muted">{{ comment.date_posted.strftime('%Y-%m-%d') }}</small>
              </div>
              <p class="article-content">{{ comment.comment }}</p>
            </div>
          </article>
        {% endfor %}
      </div>
  </div>
  
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h3 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h3>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.account_user', userid=post.author.id) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}